from src.ingestion.weather_client import get_weather
from src.ingestion.multiple_city_weather_client import multiple_city_weather
from src.ingestion.meteostat_loader import load_historical_weather_data